module.exports = {
    active: 'dev',
    webEntry: [
        'index',
        // 'view/article/index',
        // 'view/article/search',
        // 'view/forum/add',
        // 'view/forum/follow',
        //  'view/forum/homepage',
        'view/forum/index',
        // 'view/forum/search',
        // 'view/home/index',
        // 'view/home/search',
        'view/index',
        // 'view/login/fast',
        // 'view/login/forget',
        // 'view/login/index',
        // 'view/login/password',
        // 'view/login/register',
        // 'view/member/bookmark',
        // 'view/member/follow',
        // 'view/member/homepage',
        // 'view/member/index',
        // 'view/member/message',
        // 'view/member/pet',
        // 'view/member/profile',
        // 'view/member/qrcode',
        // 'view/service/index',
        // 'view/shop/index',
        // 'view/sns/index',
        // 'view/topic/add',
        'view/topic/detail',
        'view/topic/index',
        // 'view/topic/like',
        // 'view/topic/location',
        // 'view/topic/remind',
        // 'view/topic/search',
        // 'view/topic/tag'
    ]
};