module.exports = {
    active: 'dev',
    webEntry: {
        // 'index': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/index.js?entry=true',
        // 'view/article/index': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/article/index.js?entry=true',
        // 'view/article/search': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/article/search.js?entry=true',
        // 'view/forum/add': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/forum/add.js?entry=true',
        // 'view/forum/follow': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/forum/follow.js?entry=true',
        // 'view/forum/homepage': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/forum/homepage.js?entry=true',
        // 'view/forum/index': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/forum/index.js?entry=true',
        // 'view/forum/search': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/forum/search.js?entry=true',
        // 'view/home/index': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/home/index.js?entry=true',
        // 'view/home/search': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/home/search.js?entry=true',
        'view/index': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/index.js?entry=true',
        // 'view/login/fast': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/login/fast.js?entry=true',
        // 'view/login/forget': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/login/forget.js?entry=true',
        // 'view/login/index': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/login/index.js?entry=true',
        // 'view/login/password': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/login/password.js?entry=true',
        // 'view/login/register': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/login/register.js?entry=true',
        // 'view/member/bookmark': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/member/bookmark.js?entry=true',
        // 'view/member/follow': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/member/follow.js?entry=true',
        // 'view/member/homepage': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/member/homepage.js?entry=true',
        // 'view/member/index': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/member/index.js?entry=true',
        // 'view/member/message': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/member/message.js?entry=true',
        // 'view/member/pet': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/member/pet.js?entry=true',
        // 'view/member/profile': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/member/profile.js?entry=true',
        // 'view/member/qrcode': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/member/qrcode.js?entry=true',
        // 'view/service/index': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/service/index.js?entry=true',
        // 'view/shop/index': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/shop/index.js?entry=true',
        // 'view/sns/index': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/sns/index.js?entry=true',
        // 'view/topic/add': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/topic/add.js?entry=true',
        // 'view/topic/detail': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/topic/detail.js?entry=true',
        // 'view/topic/index': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/topic/index.js?entry=true',
        // 'view/topic/like': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/topic/like.js?entry=true',
        // 'view/topic/location': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/topic/location.js?entry=true',
        // 'view/topic/remind': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/topic/remind.js?entry=true',
        // 'view/topic/search': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/topic/search.js?entry=true',
        // 'view/topic/tag': '/Users/zhongyongqiang/Documents/Workspace/NowUI-Mobile/.temp/view/topic/tag.js?entry=true'
    }
};