module.exports = {
    active: 'dev',
    webEntry: [
        'index',
        // 'article/index',
        // 'article/search',
        'forum/add',
        // 'forum/follow',
        // 'forum/homepage',
        // 'forum/index',
        // 'forum/search',
        // 'home/index',
        // 'home/search',
        // 'login/fast',
        // 'login/forget',
        // 'login/index',
        // 'login/password',
        // 'login/register',
        // 'member/bookmark',
        // 'member/follow',
        // 'member/homepage',
        // 'member/index',
        // 'member/message',
        // 'member/pet',
        // 'member/profile',
        // 'member/qrcode',
        // 'service/index',
        // 'shop/index',
        // 'sns/index',
        // 'topic/add',
        // 'topic/detail',
        // 'topic/index',
        // 'topic/like',
        // 'topic/location',
        // 'topic/remind',
        // 'topic/search',
        // 'topic/tag'
    ]
};